[advisories]
ignore = []
notice = "deny"
unmaintained = "deny"
vulnerability = "deny"
yanked = "deny"

# This library uses the MPL-2 license.
#
# See https://www.mozilla.org/en-US/MPL/2.0/permissive-code-into-mpl/
[licenses]
allow = [
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
]
default = "deny"
confidence-threshold = 1.0
unlicensed = "deny"

[bans]
allow = []
deny = [
    # License is non-trivial
    { name = "ring" },
]
multiple-versions = "deny"
skip = [
    # Transitive dependency of both redox_syscall and rustix (rustix has newer).
    #
    # Only one version of bitflags ultimately gets compiled in due to OS-based feature flags in tempfile.
    { name = "bitflags" },
    # Conflict between bcrypt and pwhash
    { name = "blowfish" },
    # Conflict between bcrypt and pwhash
    { name = "cipher" },
]
skip-tree = []
wildcards = "deny"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
